AllCops:
  Exclude:
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**
    - lib/tasks/sample.rake
    - lib/jellyfish_fog_aws/spec/dummy/**/*
    - test/**/*
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

ClassLength:
  Max: 300

MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 50

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 38

Style/Alias:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$evm]

Style/IfUnlessModifier:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

GuardClause:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PredicateName:
  NameWhitelist:
    - has_one
    - has_many
    - is_manager?
    - is_admin?
    - manageiq-client.rb

Style/AndOr:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Max: 6
